import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test, describe } from 'node:test';

import { keccak256, encodePacked, type Address, type Hex } from 'viem';

import { instructionAt, writeSlot, nextOp, type Op } from '../lib/source-codec.js';
import {
  GENESIS_SOURCE_HASH,
  SOURCE_HASH_PREIMAGE_BYTES,
  chainSourceHash,
  chainSourceHashes,
  nextSourceHash,
  sourceHashPreimage,
} from '../lib/source-hash.js';

/**
 * The parity fixture is generated by `forge test --match-test test_WriteParityFixture`, running
 * the transition and hashing code copied verbatim from `SOURCE._advanceSource`. Replaying it here
 * is what proves the TypeScript hash is the Solidity hash, not merely a plausible reimplementation.
 */
interface ParityFixture {
  chainId: number;
  contract: Address;
  genesisHash: Hex;
  changes: Array<{
    revision: number;
    slot: number;
    oldOp: number;
    newOp: number;
    isBuy: boolean;
    newState: number;
    newHash: Hex;
  }>;
}

const fixture = JSON.parse(
  readFileSync(path.join(import.meta.dirname, 'fixtures', 'solidity-parity.json'), 'utf8'),
) as ParityFixture;

describe('Source Hash parity with Solidity', () => {
  test('the fixture really came from Solidity and covers two full releases', () => {
    assert.equal(fixture.changes.length, 64, '64 changes = two releases of 32');
    assert.equal(fixture.genesisHash, GENESIS_SOURCE_HASH);
    assert.equal(fixture.chainId, 1);
  });

  test('replaying the fixture reproduces every Solidity hash and state', () => {
    let state = 0;
    let hash = fixture.genesisHash;

    for (const [index, change] of fixture.changes.entries()) {
      // the transition the TypeScript derives must be the one Solidity recorded
      const oldOp = instructionAt(state, change.slot);
      assert.equal(oldOp, change.oldOp, `change ${index}: oldOp`);
      assert.equal(nextOp(oldOp, change.isBuy), change.newOp, `change ${index}: newOp`);

      state = writeSlot(state, change.slot, change.newOp as Op);
      assert.equal(state, change.newState, `change ${index}: packed state`);

      hash = nextSourceHash(hash, {
        chainId: BigInt(fixture.chainId),
        contractAddress: fixture.contract,
        revision: BigInt(change.revision),
        newState: state,
        slot: change.slot,
        oldOp: change.oldOp as Op,
        newOp: change.newOp as Op,
        isBuy: change.isBuy,
      });
      assert.equal(hash, change.newHash, `change ${index}: Source Hash`);
    }
  });

  test('chainSourceHash folds the whole fixture to the same final hash', () => {
    const inputs = fixture.changes.map((change) => ({
      chainId: BigInt(fixture.chainId),
      contractAddress: fixture.contract,
      revision: BigInt(change.revision),
      newState: change.newState,
      slot: change.slot,
      oldOp: change.oldOp as Op,
      newOp: change.newOp as Op,
      isBuy: change.isBuy,
    }));
    const last = fixture.changes[fixture.changes.length - 1];
    assert.equal(chainSourceHash(fixture.genesisHash, inputs), last?.newHash);

    const all = chainSourceHashes(fixture.genesisHash, inputs);
    assert.equal(all.length, fixture.changes.length);
    for (const [index, change] of fixture.changes.entries()) {
      assert.equal(all[index], change.newHash, `intermediate hash ${index}`);
    }
  });
});

describe('Source Hash preimage', () => {
  const base = {
    chainId: 1n,
    contractAddress: '0x00000000000000000000000000000000000c0dE1' as Address,
    revision: 7n,
    newState: 0x0000_0f0f,
    slot: 3,
    oldOp: 0 as Op,
    newOp: 1 as Op,
    isBuy: true,
  };

  test('is exactly 124 bytes: 32+32+20+32+4+1+1+1+1', () => {
    const preimage = sourceHashPreimage(GENESIS_SOURCE_HASH, base);
    assert.equal((preimage.length - 2) / 2, SOURCE_HASH_PREIMAGE_BYTES);
    assert.equal(SOURCE_HASH_PREIMAGE_BYTES, 32 + 32 + 20 + 32 + 4 + 1 + 1 + 1 + 1);
  });

  test('packs each field at its Solidity width', () => {
    const preimage = sourceHashPreimage(GENESIS_SOURCE_HASH, base);
    const expected = encodePacked(
      ['bytes32', 'uint256', 'address', 'uint256', 'uint32', 'uint8', 'uint8', 'uint8', 'bool'],
      [
        GENESIS_SOURCE_HASH,
        base.chainId,
        base.contractAddress,
        base.revision,
        base.newState,
        base.slot,
        base.oldOp,
        base.newOp,
        base.isBuy,
      ],
    );
    assert.equal(preimage, expected);
    assert.equal(nextSourceHash(GENESIS_SOURCE_HASH, base), keccak256(expected));
  });

  test('the chain starts from the zero hash', () => {
    assert.equal(GENESIS_SOURCE_HASH, `0x${'00'.repeat(32)}`);
  });

  test('is insensitive to the casing of the contract address', () => {
    const lower = { ...base, contractAddress: base.contractAddress.toLowerCase() as Address };
    assert.equal(nextSourceHash(GENESIS_SOURCE_HASH, lower), nextSourceHash(GENESIS_SOURCE_HASH, base));
  });

  test('every field is committed to: changing any one changes the hash', () => {
    const reference = nextSourceHash(GENESIS_SOURCE_HASH, base);
    const variants: Array<[string, Hex]> = [
      ['previousHash', nextSourceHash(`0x${'11'.repeat(32)}`, base)],
      ['chainId', nextSourceHash(GENESIS_SOURCE_HASH, { ...base, chainId: 2n })],
      [
        'contract',
        nextSourceHash(GENESIS_SOURCE_HASH, {
          ...base,
          contractAddress: '0x00000000000000000000000000000000000C0dE2' as Address,
        }),
      ],
      ['revision', nextSourceHash(GENESIS_SOURCE_HASH, { ...base, revision: 8n })],
      ['newState', nextSourceHash(GENESIS_SOURCE_HASH, { ...base, newState: 0x0000_0f0e })],
      ['slot', nextSourceHash(GENESIS_SOURCE_HASH, { ...base, slot: 4 })],
      ['oldOp', nextSourceHash(GENESIS_SOURCE_HASH, { ...base, oldOp: 1, newOp: 2 })],
      ['isBuy', nextSourceHash(GENESIS_SOURCE_HASH, { ...base, isBuy: false })],
    ];
    for (const [label, hash] of variants) {
      assert.notEqual(hash, reference, `changing ${label} must change the Source Hash`);
    }
  });

  test('rejects malformed inputs rather than hashing garbage', () => {
    assert.throws(() => nextSourceHash('0xdead' as Hex, base), /32-byte/);
    assert.throws(() => nextSourceHash(GENESIS_SOURCE_HASH, { ...base, slot: 16 }), /invalid slot/);
    assert.throws(() => nextSourceHash(GENESIS_SOURCE_HASH, { ...base, newOp: 4 as Op }), /invalid newOp/);
    assert.throws(
      () => nextSourceHash(GENESIS_SOURCE_HASH, { ...base, newState: 0x1_0000_0000 }),
      /uint32/,
    );
    assert.throws(() => nextSourceHash(GENESIS_SOURCE_HASH, { ...base, revision: -1n }), /non-negative/);
    assert.throws(
      () => nextSourceHash(GENESIS_SOURCE_HASH, { ...base, contractAddress: 'nope' as Address }),
      /not an address/,
    );
  });

  test('the chain is order-dependent: swapping two changes changes the result', () => {
    const a = { ...base, revision: 1n };
    const b = { ...base, revision: 2n, slot: 5 };
    assert.notEqual(
      chainSourceHash(GENESIS_SOURCE_HASH, [a, b]),
      chainSourceHash(GENESIS_SOURCE_HASH, [b, a]),
    );
  });
});
